owner: digitalservicebund
repo: uptime-monitor

sites:
  - name: Grundsteuer
    url: https://www.grundsteuererklaerung-fuer-privateigentum.de/?check=upptime
    icon: https://www.grundsteuererklaerung-fuer-privateigentum.de/favicon.ico
    maxResponseTime: 5000
    verbose: true

  - name: DigitalService Website
    url: https://digitalservice.bund.de/

  - name: STL-Rente
    url: https://www.steuerlotse-rente.de/
    icon: https://www.steuerlotse-rente.de/icons/favicon-7513565893cdbbe9a25aff1019125837.png
    maxResponseTime: 5000
    # Fix alert noise. More details here: https://github.com/digitalservicebund/platform/issues/494
    expectedStatusCodes:
      - 200
      - 0
    
  - name: service.justiz.de
    url: https://service.justiz.de/
    icon: https://service.justiz.de/favicon.ico
    maxResponseTime: 5000

  - name: Neuris
    url: https://ris.prod.ds4g.net/
    maxResponseTime: 5000

  - name: Digitalcheck Werkzeugfinder
    url: https://digitalcheck-tool-finder.prod.ds4g.net/
    maxResponseTime: 5000
    
  - name: Digitalcheck Regelungen erarbeiten
    url: https://erarbeiten.digitalcheck.bund.de/
    maxResponseTime: 5000

  - name: Track-Your-Time
    url: https://track-your-time.prod.ds4g.net/
    maxResponseTime: 5000

  - name: Metabase
    url: https://kpi.digitalservice.dev/
    maxResponseTime: 5000

  - name: N8N
    url: https://metrics.ds4g.dev:56780/
    maxResponseTime: 5000

  - name: NocoDB
    url: https://metrics.ds4g.dev:38081/
    maxResponseTime: 5000
    
status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  baseUrl: /uptime-monitor
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: DigitalService status
  introTitle: "**DigitalService** Service Status"
  introMessage: Für ein digitales Deutschland
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/digitalservicebund
    - title: Webseite
      href: https://digitalservice.bund.de/
